### ISSUE TITLE
vs-overlay issue

### ISSUE THREAD

**Issue by challenger087** [MiggL/Shieldbreakers-StreamControl-setup#10]
Hi MiggL ! any idea to fix that problem ? the name of players too not show properly
https://i.ibb.co/BynkJXj/Capture.png

Here's the code : 

**VS_Overlay**
https://we.tl/t-nxpKRbqEyg

**scoreboard-updater**
https://we.tl/t-zB1ujihser

Overlay : https://i.ibb.co/DLP3gcn/vs-overlay.png
The image of players is set to 500x667

**Comment by MiggL** [comment]
You're missing the code to display the second name
Under line 30 in the html-file, add this line
`board.addChild(newMirroredDynText("pName2", "pName1"));`

**Comment by challenger087** [comment]
My bad ! i did not notice this line is missing -_-,  the image is fixed too :)
Thx a lot !
