### ISSUE TITLE
Issue using Set Bracket Data

### ISSUE THREAD

**Issue by CharcoalAttack** [MiggL/Shieldbreakers-StreamControl-setup#14]
Hey everyone,

Really enjoying messing around with the challonge API and was super happy to see that most of the functionality works on streamcontrol, but I can't seem to make the Set Bracket Data button pull the into into the top 8 bracket tab. Is this a known issue or am I using the application wrong somehow?

![image](https://user-images.githubusercontent.com/50971179/167702847-778fb385-f22f-4205-a675-d71c64223637.png)

![image](https://user-images.githubusercontent.com/50971179/167702932-2ec8730a-ce6d-4e8f-ba00-3bb02cdf681c.png)

**Comment by MiggL** [comment]
Hi! Thank you for trying out my setup.

Is your test tournament is a single elimination bracket? To my understanding, that button only works for double elimination brackets.

**Comment by CharcoalAttack** [comment]
It was a double elimination tournament. I'm not sure if it was an issue with the number of participants, but I did make two test brackets beforehand to test single/double elimination tournaments and neither seemed to work. Here is the most recent [bracket](https://challonge.com/TBGGACT).

**Comment by MiggL** [comment]
It works for me with the bracket you linked.
![image](https://user-images.githubusercontent.com/13435195/170830632-08ee54b6-9610-48d6-83ba-23c1b17ac621.png)
![image](https://user-images.githubusercontent.com/13435195/170830677-7628d6d0-8fe1-4cbb-afa5-e63d1b31201d.png)

**Comment by CharcoalAttack** [comment]
Apologies, I was using the tournament ID incorrectly
