### ISSUE TITLE
Add commentator overlay

### ISSUE THREAD

**Issue by MiggL** [MiggL/Shieldbreakers-StreamControl-setup#8]

**Comment by MiggL** [comment]
Currently only in the standard layout file.

**Comment by groff16** [comment]
Ok downloading over to check it out now MiggL i will respond to you asap

**Comment by groff16** [comment]
Yes @MiggL  this is the greatest thank you so much man ... I would be using it this weekend for a tournament in my country. I am from Trinidad and Tobago (Caribbean Seas) my Twitch is trinidad_esports


The only thing left is flags in the top 8 section and i am a happy guy all the way from the Caribbean. thank you so much man i appreciate your good work here

**Comment by groff16** [comment]
@MiggL good day bro i came to ask you if you can put a swap button for the commentators. 

And by the Twitter names and Twitter ID once you put in the names their id stick to their names so when you just time the name of the commentator it will put in all the info for them once entered. That is all i would like to get please thanks. 

Hope all is well on your end with family and friends ... be safe ...

**Comment by MiggL** [comment]
Hi,
I updated the layout file `streamcontrol.xml` to fulfill your requests. You can swap the commentators and it will remember and associate the twitter id.

As for flags in the top 8 section, that will require more work but I may spend time on it during the next month.

Everyone close to me is safe, thanks for your concern. I hope you're okay as well in these hard times.

**Comment by groff16** [comment]
OMG thank you @MiggL  you are a god ...

**Comment by MiggL** [comment]
You're welcome!
Note that it's preferable to create new issues for new requests. Subscribe to https://github.com/MiggL/Shieldbreakers-StreamControl-setup/issues/13 for future updates on bracket flags. Cheers.
